USE [master]
GO

/****** Object:  Database [iBee]    Script Date: 05/25/2009 20:14:37 ******/
CREATE DATABASE [iBee] ON  PRIMARY 
( NAME = N'iBee', FILENAME = N'C:\Archivos de programa\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\iBee.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'iBee_log', FILENAME = N'C:\Archivos de programa\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\iBee_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [iBee] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [iBee].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [iBee] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [iBee] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [iBee] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [iBee] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [iBee] SET ARITHABORT OFF 
GO

ALTER DATABASE [iBee] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [iBee] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [iBee] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [iBee] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [iBee] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [iBee] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [iBee] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [iBee] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [iBee] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [iBee] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [iBee] SET  DISABLE_BROKER 
GO

ALTER DATABASE [iBee] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [iBee] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [iBee] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [iBee] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [iBee] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [iBee] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [iBee] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [iBee] SET  READ_WRITE 
GO

ALTER DATABASE [iBee] SET RECOVERY FULL 
GO

ALTER DATABASE [iBee] SET  MULTI_USER 
GO

ALTER DATABASE [iBee] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [iBee] SET DB_CHAINING OFF 
GO


